name: Auto Deploy Flask with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: SSH and Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd DTS-CERTIFICATE || git clone https://github.com/Thamizharasan-s24/Certificate.git && cd DTS-CERTIFICATE
          git pull origin main
          docker build -t flask-app .
          docker stop flask-container || true
          docker rm flask-container || true
          docker run -d -p 80:80 --restart always --name flask-container flask-app
